#define TOLERABLE_SERVICE_ERROR 0.80
#define GENERATOR_WARMER 1000

#define DEFAULT_CELL_RADIUS 0.0

#define DEFAULT_WIFICELL_RADIUS 0.060
#define DEFAULT_WIFI_BANDWIDTH 54000 
#define DEFAULT_WIFI_BROADCAST_BANDWIDTH 1024 

#define DEFAULT_UMTSCELL_RADIUS 1.0 
#define DEFAULT_UMTS_BANDWIDTH 57000
#define DEFAULT_UMTS_BROADCAST_BANDWIDTH 1512 
